### ISSUE TITLE
fix `#FIXME`s

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.executive.summary#104]
we tagged a bunch of things, primarily adding `eval = FALSE` to Rmd chunks, with `#FIXME` so there easy to find. We should search for any of these and fix them before release.

- [x] diagram #110
- [x] scatter https://github.com/RMI-PACTA/pacta.executive.summary/blob/65dcf747bb6a7b68d16bc2d0168ebcc20dba51e3/inst/extdata/PA2022CH_en_exec_summary/template.Rmd#L153
- [x] scores https://github.com/RMI-PACTA/pacta.executive.summary/blob/65dcf747bb6a7b68d16bc2d0168ebcc20dba51e3/inst/extdata/PA2022CH_en_exec_summary/template.Rmd#L195
- [x] alignment_table_bonds https://github.com/RMI-PACTA/pacta.executive.summary/blob/65dcf747bb6a7b68d16bc2d0168ebcc20dba51e3/inst/extdata/PA2022CH_en_exec_summary/template.Rmd#L232
- [x] alignment_table_equity https://github.com/RMI-PACTA/pacta.executive.summary/blob/65dcf747bb6a7b68d16bc2d0168ebcc20dba51e3/inst/extdata/PA2022CH_en_exec_summary/template.Rmd#L243
- [x] real estate section https://github.com/RMI-PACTA/pacta.executive.summary/blob/957128365c928ca733b34bff6c06410a39cfdc84/inst/extdata/PA2022CH_en_exec_summary/template.Rmd#L276
- [x] exposures_scorecard https://github.com/RMI-PACTA/pacta.executive.summary/blob/65dcf747bb6a7b68d16bc2d0168ebcc20dba51e3/inst/extdata/PA2022CH_en_exec_summary/template.Rmd#L513
- [x] scores_scorecard https://github.com/RMI-PACTA/pacta.executive.summary/blob/65dcf747bb6a7b68d16bc2d0168ebcc20dba51e3/inst/extdata/PA2022CH_en_exec_summary/template.Rmd#L524
- [x] #133

**Comment by cjyetman** [comment]
#112 fixes two of these

**Comment by jdhoffa** [comment]
For reference, FIXME's are currently on code chunks on the `template.Rmd` labelled: 

- [ ] diagram
- [ ] scatter
- [ ] scores
- [ ] alignment_table_bonds
- [ ] alignment_table_equity
- [ ] exposures_scorecard
- [ ] scores_scorecard

**Comment by cjyetman** [comment]
another fixed in #110

**Comment by jdhoffa** [comment]
I believe there are still open bugs in the scatter plot, not entirely addressed by #112

**Comment by cjyetman** [comment]
I moved the list to the first comment so that the task list status is visible in the issues list

**Comment by MonikaFu** [comment]
I marked exposures as done as they appear now. Also RE section is enabled except for the chart, right @AlexAxthelm ?
