### ISSUE TITLE
dependencies only used in the Rmd template cause a note in R CMD check

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.executive.summary#105]
New R pkg dependencies ({grid}, {gridExtra}, and {png}) added in #99 are only used in [inst/ext/PA2022CH_en_exec_summary/survey-chapter.Rmd](https://github.com/RMI-PACTA/pacta.executive.summary/blob/01a13e88c9e508c9f68c444a03da9f27779c5f2a/inst/extdata/PA2022CH_en_exec_summary/survey-chapter.Rmd#L58) which results in a note in R CMD check:
``` sh
❯ checking dependencies in R code ... NOTE
  Namespaces in Imports field not imported from:
    ‘grid’ ‘gridExtra’ ‘png’
    All declared Imports should be used.
```

maybe @jdhoffa knows the best way to deal with this?

**Comment by jdhoffa** [comment]
Add it to `Suggests`

**Comment by jdhoffa** [comment]
Similar to in `pacta.data.preparation`, there are packages in `run_pacta_data_preparation`, that aren't in the actual package:
https://github.com/RMI-PACTA/pacta.data.preparation/blob/e0ee8c95adc3cd8f5778021b25b39442ac3acfb0/DESCRIPTION#L57-L65

Then in the `Dockerfile` we make sure to call `install_deps(..., dependencies = TRUE)` or `install(..., dependencies = TRUE)`: 
https://github.com/RMI-PACTA/pacta.data.preparation/blob/e0ee8c95adc3cd8f5778021b25b39442ac3acfb0/Dockerfile#L9

**Comment by jdhoffa** [comment]
Note, the `dependencies` argument is sorta weird lol: 

``` md
dependencies
Which dependencies do you want to check? Can be a character vector (selecting from "Depends", "Imports", "LinkingTo", "Suggests", or "Enhances"), or a logical vector.

TRUE is shorthand for "Depends", "Imports", "LinkingTo" and "Suggests". NA is shorthand for "Depends", "Imports" and "LinkingTo" and is the default. FALSE is shorthand for no dependencies (i.e. just check this package, not its dependencies).

The value "soft" means the same as TRUE, "hard" means the same as NA.

You can also specify dependencies from one or more additional fields, common ones include:

Config/Needs/website - for dependencies used in building the pkgdown site.

Config/Needs/coverage for dependencies used in calculating test coverage.

```

**Comment by jdhoffa** [comment]
Basically the gist is the following: 
* inst contains some template `.Rmd` files. They are cool, and show how you might use the functions within the `pacta.executive.summary` repo, but are not necessary to actually execute all exported functions from the package
* any deps that the `.Rmd` files themselves have, are not actually hard dependencies of the package (even if, for our purposes, they are hard dependencies, since the only thing we want to do is run the .Rmd files) 
* so it's important that our TM workflow installs the suggested packages of ALL of our pacta.* dependencies, because whatever we are "suggesting" is exactly how TM should run hahaha

**Comment by cjyetman** [comment]
> Add it to `Suggests`

But then we have to be cautious about how we install the package in the Docker image.... I believe by default `Suggests` do not get installed, but we will definitely need them there.

**Comment by jdhoffa** [comment]
> > Add it to `Suggests`
> 
> But then we have to be cautious about how we install the package in the Docker image.... I believe by default `Suggests` do not get installed, but we will definitely need them there.

See above
