### ISSUE TITLE
Filter out indices

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/pacta.executive.summary#111]
Currently, all indices are returned after general `data_prep_executive_summary()`. There should be only one index per asset class.

**Comment by jdhoffa** [comment]
> Currently, all indices are returned after general `data_prep_executive_summary()`. There should be only one index per asset class.

There are currently 3 possible indices to choose from for the asset_class "Equity". So I guess this means we will need to decide which index should be plotted for Equity?

**Comment by MonikaFu** [comment]
Yes. At the same time in the ES draft the one plotted was MSCI world so I guess we could go with that bascially.

**Comment by jacobvjk** [comment]
if we want to avoid Silvia's wrath we need to go with the ones in the lookup file
