### ISSUE TITLE
Explore removing `xelatex` dependency

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/pacta.executive.summary#135]
with #73 closed, we may not have unicode issues any more. could we remove our xelatex dependency?

https://github.com/RMI-PACTA/pacta.executive.summary/blob/6c63858cf25011273533d60b819abdd991f959f2/inst/extdata/PA2022CH_en_exec_summary/template.Rmd#L4

**Comment by cjyetman** [comment]
related https://github.com/RMI-PACTA/workflow.transition.monitor/issues/43

**Comment by cjyetman** [comment]
I suggest we postpone this until everything is done-ish.

**Comment by cjyetman** [comment]
I'm not sure what for, but ultimately we went back to relying on xelatex, so I guess this issue should be closed until we have a reason to remove xelatex again. @AlexAxthelm?
