### ISSUE TITLE
check that correct scenario thresholds are used in visuals

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/pacta.executive.summary#160]
we compare with GECO 1.5, NDC-LTS and CurPol. Those correspond to thresholds of 1.5, 1.8 and 3 degrees

in some static pics we may still be using 2°

**Comment by MonikaFu** [comment]
Now I remember that there was a discussion about it at some point but no follow up :/ does it mean that for alignment scores we use different scenarios for different sectors, meaning I can't quote one temperature for entire chart?

**Comment by jacobvjk** [comment]
no, it means that we only consider sectors for which there are trajectories in GECO 2021, and for all those sectors the above scenarios are given. The one that determines the "cutoff" if you will is the second most ambitious scenario, which is NDC-LTS. And NDC-LTS corresponds to a 1.8 degrees estimate, not a 2° estimate. 2° was always a wrong number, once GECO was picked. So they just all need to refer to 1.8°

**Comment by MonikaFu** [comment]
thanks @jacobvjk ! That is much easier to solve 😄
