### ISSUE TITLE
follow up needed for scenario threshold change, all else lgtm

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.executive.summary#164]
follow up needed for scenario threshold change, all else lgtm

(Not sure exactly what this refers to, but just flagging in a new issue to make sure it doesn't get missed) 

_Originally posted by @jacobvjk in https://github.com/RMI-PACTA/pacta.executive.summary/pull/158#pullrequestreview-1187047881_

**Comment by jacobvjk** [comment]
already covered by #160

**Comment by jdhoffa** [comment]
Sweet :-)
