### ISSUE TITLE
fix formatting of links

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.executive.summary#178]

**Comment by jdhoffa** [comment]
In particular, links currently appear with full URL. Should be switched to just "link"

**Comment by jdhoffa** [comment]
I think this is closed? 
<img width="590" alt="Screen Shot 2022-11-23 at 12 40 52 PM" src="https://user-images.githubusercontent.com/8741309/203538010-1784608f-da92-4dc1-a13f-f106745e73cc.png">

**Comment by cjyetman** [comment]
There are many more links than those two I think... FYI

**Comment by jdhoffa** [comment]
Yup fair enough. Misformatted here:

- [ ]  <img width="850" alt="Screen Shot 2022-11-23 at 12 43 29 PM" src="https://user-images.githubusercontent.com/8741309/203538524-f3a25a87-cfc5-4cfe-909d-3f448681aca7.png">

- [ ] <img width="361" alt="Screen Shot 2022-11-23 at 12 43 50 PM" src="https://user-images.githubusercontent.com/8741309/203538584-1d513282-e715-420e-82fd-b399fc178d31.png">
