### ISSUE TITLE
Difference in exposures in ES and Scorecard

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/pacta.executive.summary#191]
Reported by Maarten:

> in the EN ES the exposures on page 2 "Exposure* to climate-relevant sectors & technologies as % of AUM" the numbers are not the same as on the Climate Score Card Page 13. Should be exactly the same. The Score Card shows 0%

**Comment by jdhoffa** [comment]
because basically there is like different categories in our PACTA summary compared to the score-card. It's confusing and it might be that. 
- Monika

**Comment by jdhoffa** [comment]
Closing this issue, because these exposure values are not identical. The first is in PACTA sectors, the second is only in a subset of PACTA sectors.

**Comment by MonikaFu** [comment]
I need more information on which numbers exactly are not the same. The charts in PACTA section are on sectoral level and the ones in the scorecard are on the technology level (kind of). It's an artifact of scorecard requirements. In scorecard we only show exposure to Coal (and in PACTA section all Fossil Fuels are grouped), Renewables Power and Fossil Power (the last two are grouped together in PACTA section but the totals seem to match in the example portfolios we're looking at)

**Comment by MonikaFu** [comment]
I talked with Maarten about it. Two issues:
* rounding obscures some of the numbers
* footnote for 'green_brown_bars' is wrong.
