### ISSUE TITLE
Aggregated climate alignment score displaying exposure as % of PACTA sectors

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.executive.summary#214]
Makes it seem too high? I dunno what this should be honestly, I think @jacobvjk has more context (or may have already solved this lol)

<img width="411" alt="Screen Shot 2022-11-22 at 8 28 07 PM" src="https://user-images.githubusercontent.com/8741309/203404144-c5c9f12c-3fbd-410d-9a3b-0e73542ca3d7.png">

**Comment by jacobvjk** [comment]
already fixed in #199
