### ISSUE TITLE
Reflow Scorecard

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/pacta.executive.summary#235]
In screenshot below, content in the blue box should be on the same page, and directly left of the content in the pink box. Content in the brown box should be kept together, but can be rearranged and located however is convenient

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/2974734/203553807-d5d2100c-cc8a-493d-8b5c-15070546358e.png">

**Comment by jdhoffa** [comment]
How's this? 
![Screen Shot 2022-11-23 at 5 31 58 PM](https://user-images.githubusercontent.com/8741309/203599233-c0edba56-3123-4929-aa95-ce5df361a236.png)

![Screen Shot 2022-11-23 at 5 32 10 PM](https://user-images.githubusercontent.com/8741309/203599295-f1a9e1af-dad2-420c-bbee-996466b9731c.png)
