### ISSUE TITLE
convert REPO_PAT to GITHUB_TOKEN

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/pacta.executive.summary#271]
https://github.com/RMI-PACTA/pacta.executive.summary/blob/3cb4f432bcd42862cabcd64fc914fa98287289d3/.github/workflows/render-readme.yml#L15

Is there a reason that this action needs to use an actual GitHub PAT< rather than the auto-generated one?

cc @cjyetman @jdhoffa

**Comment by jdhoffa** [comment]
Not that I know of
