### ISSUE TITLE
Delete the failing action

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/pacta.executive.summary#301]
> @cjyetman you mean delete the failing action?

you have two reasonable options:
1. ignore the failing test here and merge this PR
2. close this PR and open a new one that completely removes the [.github/workflows/add-prs-and-issues-to-project.yml](https://github.com/RMI-PACTA/pacta.executive.summary/blob/main/.github/workflows/add-prs-and-issues-to-project.yml)

_Originally posted by @cjyetman in https://github.com/RMI-PACTA/pacta.executive.summary/issues/299#issuecomment-2067587307_

**Comment by MonikaFu** [comment]
I'd rather delete it as I don't want to keep it in my working memory when it fails and when it doesn't :) especially since I'm not using the project the action relates to. But if you think it should stay and be linked to that project board then I will keep it.

**Comment by jdhoffa** [comment]
Sounds good, I don't mind at all, I also don't use it :-) 

(but fyi @cjyetman)
