### ISSUE TITLE
ci/cd: 5/8 checks failing

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.executive.summary#309]
@cjyetman @MonikaFu just noting that this was merged with 5/8 checks failing. 

Please look into that ASAP, it still seems like a documentation issue.

_Originally posted by @jdhoffa in https://github.com/RMI-PACTA/pacta.executive.summary/issues/307#issuecomment-2100608375_

**Comment by MonikaFu** [comment]
I believe this was solved in #311 .
