### ISSUE TITLE
feat: update `remaining_carbon_budget` to include WEO2023 data

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.executive.summary#318]
See:
https://github.com/RMI-PACTA/pacta.executive.summary/blob/b89e54900a8e1b688a393bed173605e2ac5ff7d6/data-raw/remaining_carbon_budgets.R#L1-L12

This dataset only has values for GECO2021, we will need to include data for GECO2023. 
I'm not entirely sure how to do this, FYI @jacobvjk @MonikaFu 

Without the appropriate values, `prep_scores_scorecard` is unable to appropriately calculate it's values:
<img width="414" alt="Screenshot 2024-05-09 at 09 53 44" src="https://github.com/RMI-PACTA/pacta.executive.summary/assets/8741309/d0ca3a43-d74f-4112-89d8-ea554c172db1">

[AB#10968](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/10968)

**Comment by jacobvjk** [comment]
I believe I originally received these values from Nick and Antoine.

**Comment by MonikaFu** [comment]
The decision has been made to use WEO2023 in executive summary. So we need this datset for WEO2023 scenarios.

**Comment by jdhoffa** [comment]
From my understanding @Antoine-Lalechere is currently working on this :-)

**Comment by MonikaFu** [comment]
closed by #327
