### ISSUE TITLE
Resolve TODOs in scorecard text

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/pacta.executive.summary#321]
Potentially for the text explaining differences between our scorecard and Swiss someone else should have a look.

[AB#10983](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/10983)

**Comment by jdhoffa** [comment]
This seems like it's no longer relevant or present in the scorecard text.
