### ISSUE TITLE
Make sure all scores can be calculated with WEO2023

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/pacta.executive.summary#332]
When testing it seems like scores for some sectors are not calculated correctly. We get NA results for:
* steel
* cement
* aviation
We need to look into score calculation to see if it needs to be adjusted in any way because of using a different source.

[AB#11118](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/11118)

**Comment by jdhoffa** [comment]
Is this still open?

**Comment by MonikaFu** [comment]
I believe not. I think all scores calculate now right?

**Comment by jdhoffa** [comment]
I think so!
