### ISSUE TITLE
Remove dependence on indices in `score_card` directory

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/pacta.executive.summary#334]
Currently the ES process fails if there is not a copy of the index benchmarks available in the `score_card` user results directory.

Relates to https://github.com/RMI-PACTA/workflow.transition.monitor/issues/325

**Comment by MonikaFu** [comment]
isn't this done?

**Comment by AlexAxthelm** [comment]
it is. Closed in #335
