### ISSUE TITLE
Verified commitments to net zero uses 'fin_data_net_zero_targets' from 'pacta-data' and not 'user_data'

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/pacta.executive.summary#341]
As discussed 'fin_data_net_zero_targets.csv' will be prepared using a script in `workflow.prep.PA2024CH` and put in the `pacta-data` repo in Swiss docker image. This needs to be reflected in the executive summary (point to the right directory). The peer net zero shares will still live in `user_results/score_card`.

FYI @AlexAxthelm @Antoine-Lalechere 

[AB#11289](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/11289)

**Comment by jdhoffa** [comment]
As mentioned in https://github.com/RMI-PACTA/workflow.prep.PA2024CH/issues/11#issuecomment-2200313287
I'm not sure it's such a good idea to assume any strictly CH related data should be living in the `pacta-data` directory. 

Maybe we discuss this topic this week?

**Comment by MonikaFu** [comment]
this is done with #346
