### ISSUE TITLE
Add HydroCap in Renewables Energy Exposure in the Executive Summary

### ISSUE THREAD

**Issue by Antoine-Lalechere** [RMI-PACTA/pacta.executive.summary#345]
As per https://rockmtnins.sharepoint.com/:w:/r/sites/PACTA/_layouts/15/Doc.aspx?sourcedoc=%7B712A81B4-872F-49F4-A1FF-D95C3C7E55D6%7D&file=04.%20ES%20-%20Swiss%20Climate%20Scorecard.docx&nav=eyJjIjozODg1NjQzNTR9&action=default&mobileredirect=true p2, the exposure chart should not only contain Renewables but also Hydro Capacity when provided for Renewables Energy.

**Comment by jdhoffa** [comment]
Closed by https://github.com/RMI-PACTA/pacta.executive.summary/pull/347
