### ISSUE TITLE
Make sure that MSCI world is used as benchmark in scorecard emissions

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/pacta.executive.summary#351]
Since the new benchmarks have been included in pacta data, make sure those are used correctly in the scorecard.

FYI @jdhoffa I just realized this is needed when updating scorecard text.

[AB#11366](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/11366)

**Comment by jdhoffa** [comment]
This seems to be the case:
https://github.com/RMI-PACTA/pacta.executive.summary/blob/20bc483491435172c8c831ea5e3dfe9dbd98ab5d/R/prep_data_executive_summary.R#L136

https://github.com/RMI-PACTA/pacta.executive.summary/blob/20bc483491435172c8c831ea5e3dfe9dbd98ab5d/R/prep_data_executive_summary.R#L249

https://github.com/RMI-PACTA/pacta.executive.summary/blob/20bc483491435172c8c831ea5e3dfe9dbd98ab5d/R/prep_data_executive_summary.R#L265
