### ISSUE TITLE
Bug: ß turns into SS when rendering into pdf

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/pacta.executive.summary#370]
I tried so far:
\char"00DF  - turned into SS
\char"E04C - turned into SS
ß in the text and \usepackage[utf8]{inputenc} in preamble - turned into SS
\ss - failed to compile

See also ADO: https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_sprints/taskboard/P4I/2DegreesInvesting/2024_22?workitem=12039 for more context.

**Comment by jdhoffa** [comment]
Closed by https://github.com/RMI-PACTA/pacta.executive.summary/pull/377
