### ISSUE TITLE
scatter plot not working

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/pacta.executive.summary#59]
it seems like there is an issue with putting the three parts of the scatter plot together, but my `ggplot2` knowledge is too basic to understand the issue quickly. I can look into this in case you have no time @MonikaFu 
Otherwise I think it makes more sense if you look into this

This is the error that is returned in the last bit of `plot_scatter()`, where all three pieces are put together
```
Error in `[[<-.data.frame`(`*tmp*`, i, value = c(16, 1, 16, 16)) : 
  replacement has 4 rows, data has 30
```

**Comment by MonikaFu** [comment]
No problem, I will look into this before the end of this week hopefully.

**Comment by cjyetman** [comment]
This works as expected for me
```r
library(dplyr)
library(pacta.executive.summary)
plot_scatter(toy_data_scatter %>% filter(asset_class == "equity"))
```

Is there more context to how/where you were getting to this error @jacobvjk? Maybe it's dependent on the data that gets passed?

**Comment by MonikaFu** [comment]
I guess it works with `toy_data` but not with real data @jacobvjk ? Might be that it crushes when some values which are assumed to be there are missing. I will look into this tomorrow.

**Comment by MonikaFu** [comment]
@jacobvjk is it possible to get the data on which this fails?

**Comment by jacobvjk** [comment]
> It seems that this bug is caused by inputting too much (or too little) data points:
> 
> ```r
> library(dplyr)
> #> 
> #> Attaching package: 'dplyr'
> #> The following objects are masked from 'package:stats':
> #> 
> #>     filter, lag
> #> The following objects are masked from 'package:base':
> #> 
> #>     intersect, setdiff, setequal, union
> library(pacta.executive.summary)
> 
> # works
> toy_data_scatter %>% 
>   filter(asset_class == "equity") %>% 
>   plot_scatter()
> #> Assigning colours to unrecognised names in data: peers_mean, this_portfolio,
> #> peers, benchmark.
> #> Assigning colours to unrecognised names in data: peers_mean, this_portfolio, peers, benchmark.
> #> Assigning colours to unrecognised names in data: peers_mean, this_portfolio, peers, benchmark.
> ```
> 
> ![](https://camo.githubusercontent.com/ab42d235cfa7d455893f605e304ffd28fb4271c17d682a51e4e51dd1aab4603b/68747470733a2f2f692e696d6775722e636f6d2f63616e636d34502e706e67)
> 
> ```r
> # does not work
> toy_data_scatter %>% 
>   filter(asset_class == "equity") %>% 
>   filter(entity_name == "portfolio") %>% 
>   plot_scatter()
> #> Assigning colours to unrecognised names in data: this_portfolio.
> #> Assigning colours to unrecognised names in data: this_portfolio.
> #> Assigning colours to unrecognised names in data: this_portfolio.
> #> Error in `[[<-.data.frame`(`*tmp*`, i, value = c(16, 1, 16, 16)): replacement has 4 rows, data has 1
> ```
> 
> Created on 2022-11-16 with [reprex v2.0.2](https://reprex.tidyverse.org)

and I believe this may have started coming up since the number of peers was much larger in real data

**Comment by MonikaFu** [comment]
it should not be affected by the number of peers tbh, they are all of the same entity_type = peers.

**Comment by jdhoffa** [comment]
Ok I just ran the following code with: 
* totally up to data pacta-data
* the same `working_dir` outputs that @jacobvjk has apparently been using
* up to date repos + freshly installed packages

and I am able to get an output no problem: 
<img width="835" alt="Screen Shot 2022-11-16 at 3 08 10 PM" src="https://user-images.githubusercontent.com/8741309/202202163-b3a2a888-64ba-4f57-af8b-b6906b95480e.png">

**Comment by jdhoffa** [comment]
same for equity: 

<img width="771" alt="Screen Shot 2022-11-16 at 3 08 41 PM" src="https://user-images.githubusercontent.com/8741309/202202324-ebac88fa-61d2-4b37-b3c7-489cc68c041f.png">

**Comment by jdhoffa** [comment]
Well, very strange. Getting the bug still when I run on the VM: 
<img width="717" alt="Screen Shot 2022-11-16 at 4 38 30 PM" src="https://user-images.githubusercontent.com/8741309/202225132-9a30137d-592c-4203-857b-0ccd066a134f.png">
