### ISSUE TITLE
fix unicode symbols in plots (e.g. triangle dot in score plot)

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/pacta.executive.summary#61]
knitr has trouble making sense of unicode characters in ggplots when compiling the markdown to a pdf output
under the hood a `latex_engine` is being used, that default of which will error out.
setting `latex_engine: xelatex` in the document `yaml` header solved the immediate error, but the triangle symbols are now not shown.
This may have similar implications for other plots.
see also https://bookdown.org/yihui/rmarkdown-cookbook/latex-unicode.html

**Comment by jdhoffa** [comment]
Relates to https://github.com/RMI-PACTA/workflow.transition.monitor/pull/26

**Comment by MonikaFu** [comment]
Hmmmm... Ok, this is very unfortunate :/ Do I understand correctly that I should look for some other way to add the traingles to the chart?

**Comment by cjyetman** [comment]
well, this makes https://github.com/RMI-PACTA/workflow.transition.monitor/pull/26 necessary
https://github.com/RMI-PACTA/pacta.executive.summary/blob/2909e4b21fc122d58241a21ce66b6b12ffa96c18/inst/extdata/PA2022CH_en_exec_summary/template.Rmd#L4

**Comment by jacobvjk** [comment]
so xelatex simply ensures the issue does not entirely crash the rendering. But the additional lines in the docker related PR sound like some font packages were installed. So my question is essentially if the triangles show when run in docker since that merge and/or of these packages can be added to the Rmd so that latex can handle them. Not sure about any of that yet

**Comment by jdhoffa** [comment]
gotcha

**Comment by cjyetman** [comment]
I dug deep into this. I think the thing is... if we're going to use a unicode character as a `geom_point`, then we have to make sure that it is rendered into the PDF with a font that has that character... which is a can of worms.

**Comment by jacobvjk** [comment]
which means it would be best to pick another market for this I guess @cjyetman @MonikaFu ?

**Comment by cjyetman** [comment]
Unfortunately, there is not a similar built-in shape, nor a reasonable alternative.
https://ggplot2.tidyverse.org/articles/ggplot2-specs.html#sec:shape-spec

**Comment by MonikaFu** [comment]
> Unfortunately, there is not a similar built-in shape, nor a reasonable alternative. https://ggplot2.tidyverse.org/articles/ggplot2-specs.html#sec:shape-spec

yes, exactly, that was my entire reason for doing it this weird way in the first place. If I remember correctly, the alternative would be to build a `geom_polygon`for each point which was an entirely different can of worms as far as I remember :/
