### ISSUE TITLE
handling for missing parts (no survey, no real estate)

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/pacta.executive.summary#63]
- [x] placeholder section if missing real estate
- [x] placeholder section if missing survey data
- [x] handling missing user level survey data in climate score card
- [x] show only one facet for faceted plots, if either equity or bonds are missing
- [x] show zero values in flow diagram for the missing asset class
- [x] show empty plot with text "no data found" for other plots
- [x] user only has direct real estate OR mortgages #177 
- [x] handle portfolio score "energy efficiency chart" for one asset only #145 
- [x] handle situation when equity and/or bonds are given, but no holding within pacta scope  (better to handle in workflow and skip ES?)
- [x] handling for no Equity or no Bonds data

This one would have undetermined behavior because we will never create a report without PACTA results:
- [ ] handle situation when neither equity nor bonds are given, both empty (better to handle in workflow and skip ES?)

**Comment by jdhoffa** [comment]
We also need to add handling for no Equity and/ or Bonds data
