### ISSUE TITLE
consider an alternative to `DiagrammeR::grViz()`

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.executive.summary#74]
@MonikaFu @jacobvjk 

pacta.executive.summary currently uses `DiagrammeR::grViz()` [here](https://github.com/RMI-PACTA/pacta.executive.summary/blob/2909e4b21fc122d58241a21ce66b6b12ffa96c18/R/plot_diagram.R#L33), which creates a htmlwidget, which then requires {chromote} to render in a headless browser to take a screenshot so a static version can be included in the PDF, which requires a Chrome-like browser to be installed on the system. This is a rather significant dependency for the TM Docker image, so we'd like to consider alternative plots/methods for creating [this plot](https://github.com/RMI-PACTA/pacta.executive.summary/blob/2909e4b21fc122d58241a21ce66b6b12ffa96c18/inst/extdata/PA2022CH_en_exec_summary/template.Rmd#L74-L81).

**Comment by jacobvjk** [comment]
afaik this is a discussion between @MonikaFu and @AlexAxthelm ? If I am not mistaken?

**Comment by AlexAxthelm** [comment]
It looks like this is just a standard `mermaid.js` digraph. Maybe we could use `DiagrammeR::export_graph()`? I just played around with it, and it looks  like we may have to change from the mermaid syntax to DiagrammeR's node/edge syntax. I don't know how difficult that would be offhand, @MonikaFu

**Comment by cjyetman** [comment]
Let's not overthink things... this is basically for a fairly simple flowchart. I think we should be able to achieve that with ggplot without too much hassle.

**Comment by MonikaFu** [comment]
I agree, it's a very simple flow-chart. I used `DiagrammeR::grViz()` because that was the solution that was favored online but I didn't think of the implications of this choice back then. @AlexAxthelm said it should not be a problem to work with the `html` widget but I see now that it is. I will look into this asap and try to find a viable alternative.

**Comment by cjyetman** [comment]
FYI... I shared a ggplot flowchart prototype in Teams

**Comment by cjyetman** [comment]
I have a new alternative that requires two new packages, but otherwise uses the existing code...
``` r
library(pacta.executive.summary)
library(DiagrammeRsvg)
library(rsvg)

diagram_htmlwidget <- plot_diagram(toy_data_diagram)
svg_text <- DiagrammeRsvg::export_svg(diagram_htmlwidget)
rsvg::rsvg_png(
  svg = charToRaw(svg_text), 
  file = "diagram.png", 
  width = 900, 
  height = 200
)
```
![diagram](https://user-images.githubusercontent.com/1708872/201868364-d76383f7-119e-4f6a-a171-28ef80e715d0.png)

**Comment by MonikaFu** [comment]
For me, this looks good as long as it's fine to use those packages. It's easier to approve this than using ggplot as it's a completely different approach so I would need to see how it behaves in terms of placements etc. But also, honestly, both are fine at this point. As long as we get it to work.

**Comment by jdhoffa** [comment]
For what it's worth, I would vote for the second option with fewer changes

**Comment by cjyetman** [comment]
There are unfortunately a bunch of cascading system dependencies from these new packages:
https://github.com/ropensci/rsvg/blob/6d9840fe956712c4ca6a1c1e16971e2e992b0bcc/DESCRIPTION#L30
https://github.com/r-lib/svglite/blob/8f30fc6e23094027debc117e3965bc887d9964f5/DESCRIPTION#L48
https://github.com/r-lib/systemfonts/blob/99b6c630af663f382abe49cb8c596f482aa66661/DESCRIPTION#L41
https://github.com/jeroen/webp/blob/53fbd37363474c1116bfb75ea525c96f0e372831/DESCRIPTION#L15
https://github.com/ropensci/magick/blob/7b111b689638f9f979adb3272ac252d288dc09dc/DESCRIPTION#L19
https://github.com/jeroen/V8/blob/7fb0e2feafc6271c4d791917b2eb10243d6ea68d/DESCRIPTION#L16

**Comment by MonikaFu** [comment]
I see. Is it preferred I look into your `ggplot` solution then?

**Comment by jdhoffa** [comment]
> There are unfortunately a bunch of cascading system dependencies from these new packages: https://github.com/ropensci/rsvg/blob/6d9840fe956712c4ca6a1c1e16971e2e992b0bcc/DESCRIPTION#L30 https://github.com/r-lib/svglite/blob/8f30fc6e23094027debc117e3965bc887d9964f5/DESCRIPTION#L48 https://github.com/r-lib/systemfonts/blob/99b6c630af663f382abe49cb8c596f482aa66661/DESCRIPTION#L41 https://github.com/jeroen/webp/blob/53fbd37363474c1116bfb75ea525c96f0e372831/DESCRIPTION#L15 https://github.com/ropensci/magick/blob/7b111b689638f9f979adb3272ac252d288dc09dc/DESCRIPTION#L19 https://github.com/jeroen/V8/blob/7fb0e2feafc6271c4d791917b2eb10243d6ea68d/DESCRIPTION#L16

I rescind my previous answer. `ggplot` definitely preferred hahaha
