### ISSUE TITLE
no `asset_type` in `peers_climate_scorecard_survey_voting.csv`

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.executive.summary#92]
In #88 @jacobvjk added `asset_type` as one of the expected columns in `peers_climate_scorecard_survey_voting.csv` here:
https://github.com/RMI-PACTA/pacta.executive.summary/blob/5b583059c575aefcdc570d24f61b84d82dc4a074/inst/extdata/PA2022CH_en_exec_summary/template.Rmd#L559-L569

but the existing `peers_climate_scorecard_survey_voting.csv` in [user_results](https://github.com/RMI-PACTA/user_results/tree/PA2022CH) does not have an `asset_type` column:
https://github.com/RMI-PACTA/user_results/blob/PA2022CH/PA2022CH/survey/EN/peers_climate_scorecard_survey_voting.csv

**Comment by jacobvjk** [comment]
will update the user_results asap @cjyetman

**Comment by cjyetman** [comment]
resolved by https://github.com/RMI-PACTA/user_results/pull/16
